@startuml Body
class "Cuerpo Humano" {
}

abstract class "Subsistema" {
}

class "Subsistema Digestivo" --|> "Subsistema" {
}

class "Subsistema Circulatorio" --|> "Subsistema" {
}

class "Subsistema Respiratorio" --|> "Subsistema" {
}

abstract class "Organo" {
}

class "Corazón" --|> "Organo" {
}

class "Intestino" --|> "Organo" {
}

class "Pulmón" --|> "Organo" {
}

"Cuerpo Humano" *-- "Subsistema" : contiene > Composición
"Subsistema" *-- "Organo" : contiene > Composición

@enduml
